"""
Categorias do QuickDraw: nome oficial (ingles, igual ao nome do arquivo .npy) -> nome em portugues.
Se alguma categoria nao existir no servidor, o main.py avisa e pula.
"""

TODAS_AS_CLASSES = {
    "aircraft carrier": "porta-aviões",
    "airplane": "avião",
    "alarm clock": "despertador",
    "ambulance": "ambulância",
    "angel": "anjo",
    "animal migration": "migração animal",
    "ant": "formiga",
    "anvil": "bigorna",
    "apple": "maçã",
    "arm": "braço",
    "asparagus": "aspargo",
    "axe": "machado",
    "backpack": "mochila",
    "banana": "banana",
    "bandage": "curativo",
    "barn": "celeiro",
    "baseball": "bola de beisebol",
    "baseball bat": "taco de beisebol",
    "basket": "cesta",
    "basketball": "bola de basquete",
    "bat": "morcego",
    "bathtub": "banheira",
    "beach": "praia",
    "bear": "urso",
    "beard": "barba",
    "bed": "cama",
    "bee": "abelha",
    "belt": "cinto",
    "bench": "banco de praça",
    "bicycle": "bicicleta",
    "binoculars": "binóculos",
    "bird": "pássaro",
    "birthday cake": "bolo de aniversário",
    "blackberry": "amora",
    "blueberry": "mirtilo",
    "book": "livro",
    "boomerang": "bumerangue",
    "bottlecap": "tampinha",
    "bowtie": "gravata-borboleta",
    "bracelet": "pulseira",
    "brain": "cérebro",
    "bread": "pão",
    "bridge": "ponte",
    "broccoli": "brócolis",
    "broom": "vassoura",
    "bucket": "balde",
    "bulldozer": "buldôzer",
    "bus": "ônibus",
    "bush": "arbusto",
    "butterfly": "borboleta",
    "cactus": "cacto",
    "cake": "bolo",
    "calculator": "calculadora",
    "calendar": "calendário",
    "camel": "camelo",
    "camera": "câmera",
    "camouflage": "camuflagem",
    "campfire": "fogueira",
    "candle": "vela",
    "cannon": "canhão",
    "canoe": "canoa",
    "car": "carro",
    "carrot": "cenoura",
    "castle": "castelo",
    "cat": "gato",
    "ceiling fan": "ventilador de teto",
    "cell phone": "celular",
    "cello": "violoncelo",
    "chair": "cadeira",
    "chandelier": "lustre",
    "church": "igreja",
    "circle": "círculo",
    "clarinet": "clarinete",
    "clock": "relógio de parede",
    "cloud": "nuvem",
    "coffee cup": "xícara de café",
    "compass": "bússola",
    "computer": "computador",
    "cookie": "biscoito",
    "cooler": "caixa térmica",
    "couch": "sofá",
    "cow": "vaca",
    "crab": "caranguejo",
    "crayon": "giz de cera",
    "crocodile": "crocodilo",
    "crown": "coroa",
    "cruise ship": "cruzeiro",
    "cup": "copo",
    "diamond": "diamante",
    "dishwasher": "lava-louças",
    "diving board": "trampolim",
    "dog": "cachorro",
    "dolphin": "golfinho",
    "donut": "rosquinha",
    "door": "porta",
    "dragon": "dragão",
    "dresser": "cômoda",
    "drill": "furadeira",
    "drums": "bateria",
    "duck": "pato",
    "dumbbell": "halter",
    "ear": "orelha",
    "elbow": "cotovelo",
    "elephant": "elefante",
    "envelope": "envelope",
    "eraser": "borracha",
    "eye": "olho",
    "eyeglasses": "óculos",
    "face": "rosto",
    "fan": "ventilador",
    "feather": "pena",
    "fence": "cerca",
    "finger": "dedo",
    "fire hydrant": "hidrante",
    "fireplace": "lareira",
    "firetruck": "caminhão de bombeiros",
    "fish": "peixe",
    "flamingo": "flamingo",
    "flashlight": "lanterna",
    "flip flops": "chinelo",
    "floor lamp": "abajur de chão",
    "flower": "flor",
    "flying saucer": "disco voador",
    "foot": "pé",
    "fork": "garfo",
    "frog": "sapo",
    "frying pan": "frigideira",
    "garden": "jardim",
    "garden hose": "mangueira",
    "giraffe": "girafa",
    "goatee": "cavanhaque",
    "golf club": "taco de golfe",
    "grapes": "uvas",
    "grass": "grama",
    "guitar": "guitarra",
    "hamburger": "hambúrguer",
    "hammer": "martelo",
    "hand": "mão",
    "harp": "harpa",
    "hat": "chapéu",
    "headphones": "fones de ouvido",
    "hedgehog": "ouriço",
    "helicopter": "helicóptero",
    "helmet": "capacete",
    "hexagon": "hexágono",
    "hockey puck": "disco de hóquei",
    "hockey stick": "taco de hóquei",
    "horse": "cavalo",
    "hospital": "hospital",
    "hot air balloon": "balão de ar quente",
    "hot dog": "cachorro-quente",
    "hot tub": "hidromassagem",
    "hourglass": "ampulheta",
    "house": "casa",
    "house plant": "planta de vaso",
    "hurricane": "furacão",
    "ice cream": "sorvete",
    "jacket": "jaqueta",
    "jail": "prisão",
    "kangaroo": "canguru",
    "key": "chave",
    "keyboard": "teclado",
    "knee": "joelho",
    "knife": "faca",
    "ladder": "escada",
    "lantern": "lampião",
    "laptop": "notebook",
    "leaf": "folha",
    "leg": "perna",
    "light bulb": "lâmpada",
    "lighter": "isqueiro",
    "lighthouse": "farol",
    "lightning": "raio",
    "line": "linha",
    "lion": "leão",
    "lipstick": "batom",
    "lobster": "lagosta",
    "lollipop": "pirulito",
    "mailbox": "caixa de correio",
    "map": "mapa",
    "marker": "marcador",
    "matches": "fósforos",
    "megaphone": "megafone",
    "mermaid": "sereia",
    "microphone": "microfone",
    "microwave": "micro-ondas",
    "monkey": "macaco",
    "moon": "lua",
    "mosquito": "mosquito",
    "motorbike": "moto",
    "mountain": "montanha",
    "mouse": "rato",
    "moustache": "bigode",
    "mouth": "boca",
    "mug": "caneca",
    "mushroom": "cogumelo",
    "nail": "prego",
    "necklace": "colar",
    "nose": "nariz",
    "ocean": "oceano",
    "octagon": "octógono",
    "octopus": "polvo",
    "onion": "cebola",
    "oven": "forno",
    "owl": "coruja",
    "paint can": "lata de tinta",
    "paintbrush": "pincel",
    "palm tree": "palmeira",
    "panda": "panda",
    "pants": "calça",
    "paper clip": "clipe de papel",
    "parachute": "paraquedas",
    "parrot": "papagaio",
    "passport": "passaporte",
    "peanut": "amendoim",
    "pear": "pera",
    "peas": "ervilhas",
    "pencil": "lápis",
    "penguin": "pinguim",
    "piano": "piano",
    "pickup truck": "caminhonete",
    "picture frame": "porta-retrato",
    "pig": "porco",
    "pillow": "travesseiro",
    "pineapple": "abacaxi",
    "pizza": "pizza",
    "pliers": "alicate",
    "police car": "viatura",
    "pond": "lagoa",
    "pool": "piscina",
    "popsicle": "picolé",
    "postcard": "cartão-postal",
    "potato": "batata",
    "power outlet": "tomada",
    "purse": "bolsa",
    "rabbit": "coelho",
    "raccoon": "guaxinim",
    "radio": "rádio",
    "rain": "chuva",
    "rainbow": "arco-íris",
    "rake": "ancinho",
    "remote control": "controle remoto",
    "rhinoceros": "rinoceronte",
    "rifle": "rifle",
    "river": "rio",
    "roller coaster": "montanha-russa",
    "rollerskates": "patins",
    "sailboat": "veleiro",
    "sandwich": "sanduíche",
    "saw": "serra",
    "saxophone": "saxofone",
    "school bus": "ônibus escolar",
    "scissors": "tesoura",
    "scorpion": "escorpião",
    "screwdriver": "chave de fenda",
    "sea turtle": "tartaruga marinha",
    "see saw": "gangorra",
    "shark": "tubarão",
    "sheep": "ovelha",
    "shoe": "sapato",
    "shorts": "bermuda",
    "shovel": "pá",
    "sink": "pia",
    "skateboard": "skate",
    "skull": "caveira",
    "skyscraper": "arranha-céu",
    "sleeping bag": "saco de dormir",
    "smiley face": "carinha feliz",
    "snail": "caracol",
    "snake": "cobra",
    "snorkel": "snorkel",
    "snowflake": "floco de neve",
    "snowman": "boneco de neve",
    "soccer ball": "bola",
    "sock": "meia",
    "speedboat": "lancha",
    "spider": "aranha",
    "spoon": "colher",
    "spreadsheet": "planilha",
    "square": "quadrado",
    "squiggle": "rabisco",
    "squirrel": "esquilo",
    "stairs": "escadas",
    "star": "estrela",
    "steak": "bife",
    "stereo": "aparelho de som",
    "stethoscope": "estetoscópio",
    "stitches": "pontos",
    "stop sign": "placa de pare",
    "stove": "fogão",
    "strawberry": "morango",
    "streetlight": "poste de luz",
    "string bean": "vagem",
    "submarine": "submarino",
    "suitcase": "mala",
    "sun": "sol",
    "swan": "cisne",
    "sweater": "suéter",
    "swing set": "balanço",
    "sword": "espada",
    "syringe": "seringa",
    "t-shirt": "camiseta",
    "table": "mesa",
    "teapot": "bule",
    "teddy-bear": "ursinho de pelúcia",
    "telephone": "telefone",
    "television": "televisão",
    "tennis racquet": "raquete de tênis",
    "tent": "barraca",
    "tiger": "tigre",
    "toaster": "torradeira",
    "toe": "dedo do pé",
    "toilet": "vaso sanitário",
    "tooth": "dente",
    "toothbrush": "escova de dentes",
    "toothpaste": "pasta de dente",
    "tornado": "tornado",
    "tractor": "trator",
    "traffic light": "semáforo",
    "train": "trem",
    "tree": "árvore",
    "triangle": "triângulo",
    "trombone": "trombone",
    "truck": "caminhão",
    "trumpet": "trompete",
    "umbrella": "guarda-chuva",
    "underwear": "cueca",
    "van": "van",
    "vase": "vaso",
    "violin": "violino",
    "washing machine": "máquina de lavar",
    "watermelon": "melancia",
    "waterslide": "tobogã",
    "whale": "baleia",
    "wheel": "roda",
    "windmill": "moinho de vento",
    "wine bottle": "garrafa de vinho",
    "wine glass": "taça de vinho",
    "wristwatch": "relógio de pulso",
    "yoga": "ioga",
    "zebra": "zebra",
    "zigzag": "zigue-zague",
}

# As 9 classes originais (treino rapido)
CLASSES_BASICAS = {k: TODAS_AS_CLASSES[k] for k in [
    "soccer ball", "umbrella", "dog", "cat", "house", "car", "sun", "apple", "fish",
]}

# ~75 classes de objetos simples, bons para desenhar no papel
CLASSES_MEDIAS = {k: TODAS_AS_CLASSES[k] for k in [
    "airplane", "apple", "banana", "bed", "bicycle", "bird", "book", "bridge", "bus",
    "butterfly", "cake", "camera", "car", "cat", "chair", "clock", "cloud", "cow", "cup",
    "dog", "door", "duck", "elephant", "eye", "face", "fish", "flower", "fork", "giraffe",
    "guitar", "hand", "hat", "horse", "house", "key", "knife", "ladder", "leaf",
    "light bulb", "lightning", "moon", "mountain", "mushroom", "pencil", "pig", "pizza",
    "rabbit", "rainbow", "scissors", "shark", "shoe", "smiley face", "snail", "snake",
    "snowman", "soccer ball", "spider", "spoon", "star", "sun", "sword", "table", "tent",
    "tooth", "train", "tree", "truck", "umbrella", "whale", "skull", "crown",
]}
